#!/usr/bin/bash

build_tool=""

if [ -f "/usr/bin/ninja" ]; then
    build_tool="-G Ninja"
fi

if [ ! -d "./build" ]; then
    cmake -B build $build_tool -DCMAKE_EXPORT_COMPILE_COMMANDS=1 || exit 
fi
cmake --build build --config Release || exit

# ISS
# curl "https://celestrak.org/NORAD/elements/gp.php?CATNR=25544&FORMAT=tle" > haha.tle
# ALL
# curl "https://celestrak.org/norad/elements/gp.php?group=active&format=tle" > haha.tle


if [ -z $1 ]; then
    build/tests/tests || exit
    build/src/main
elif [[ $1 == *"test"* ]]; then
    build/tests/tests
else
    build/src/main
fi
